#!/system/bin/sh
# 2010-08-05 Firerat, bind mount cache to sd ext partition, and mount mtdblock4 for Clockwork recovery's use
# 2010-08-23 NLJ: slightly edited for SpeedTeam FroYo releases

if [ -z ${SD_EXT_DIRECTORY} ]
then
    SD_EXT_DIRECTORY=/sd-ext
fi

busybox umount /cache

grep -q ${SD_EXT_DIRECTORY} /proc/mounts
if [ ! $? -eq 0 ]
then
    CacheDir=/data/cache
else
    CacheDir=${SD_EXT_DIRECTORY}/cache
fi

if [ ! -d $CacheDir ];
then
	busybox install -m 771 -o 1000 -g 2001 -d $CacheDir
fi
    busybox mount -o bind $CacheDir /cache
if [ ! -d $CacheDir/dalvik-cache ];
then
	busybox install -m 771 -o 1000 -g 1000 -d $CacheDir/dalvik-cache
fi

if [ ! -d /dev/cache ];
then
	busybox install -d /dev/cache
fi

if [ "`grep -q "/dev/cache /proc/mounts;echo $?`" != "0" ];
then
	busybox mount -t yaffs2 -o nosuid,nodev /dev/block/mtdblock4 /dev/cache
fi
if [ ! -d /dev/cache/recovery ];
then
	busybox install -m 770 -o 1000 -g 2001 -d /dev/cache/recovery
fi
if [ ! -L $CacheDir/recovery ];
then
	ln -s /dev/cache/recovery $CacheDir/recovery
fi
