#!/system/bin/sh
#
# NOTICE:
# Although I've written this file from scratch (well almost =o)
# credits for this should go to Firerat and
# flames should go to me =o)
# NLJ
# 20100822 
# - first version heavily based on Firerat work
# 20100823
# - /data/data mount binded to /sd-ext/data
# - apk moved back to /data/app* in case we can't mount --bind  

if [ -z ${SD_EXT_DIRECTORY} ]
then
    SD_EXT_DIRECTORY=/sd-ext
fi

grep -q ${SD_EXT_DIRECTORY} /proc/mounts
if [ ! $? -eq 0 ]
then
    log -p e -t apps2sd "${SD_EXT_DIRECTORY} not mounted. Not enabling Apps2SD."
    exit 0
fi

for d in app app-private
do
   if [ ! -d ${SD_EXT_DIRECTORY}/${d} ]
   then
       install -m 771 -o 1000 -g 1000 -d ${SD_EXT_DIRECTORY}/${d}
       log -p i -t apps2sd "Created ${SD_EXT_DIRECTORY}/${d}"
   fi
   # Firerat's 1.3.8 had /data/app symlinked to /sd-ext/app
   # just remove it and recreate dir
   if [ -L /data/${d} ]
   then
       rm /data/${d}
       if [ ! $? -eq 0 ]
       then
           log -p e -t apps2sd "Can't remove /data/${d} symlink. Not enabling Apps2SD."
           exit 1
       fi
       install -m 771 -o 1000 -g 1000 -d /data/${d}
       if [ ! $? -eq 0 ]
       then
           log -p e -t apps2sd "Can't re-create /data/${d} dir. Not enabling Apps2SD."
           exit 1
       fi
   elif [ -d /data/${d} ]
   then
       # Move files to SD 
       find /data/${d}/ -type f >/dev/${d}_flist 
       for f in `cat /dev/${d}_flist`
       do
          mv ${f} ${SD_EXT_DIRECTORY}/${d}/
       done
       log -p e -t apps2sd "Moved apps to ${SD_EXT_DIRECTORY}/${d}"
   fi
   # Support Firerat's ApkManager.sh
   if [ ! -e /data/${d}_i ]
   then
       install -m 771 -o 1000 -g 1000 -d /data/${d}_i
   fi
   # All should be setup at this point
   busybox mount --bind ${SD_EXT_DIRECTORY}/${d} /data/${d}
   if [ $? -eq 0 ]
   then
       log -p i -t apps2sd "${SD_EXT_DIRECTORY}/${d} binded to /data/${d}"
   else
       log -p e -t apps2sd "Failed to bind ${SD_EXT_DIRECTORY}/${d} on /data/${d}"
       sed -i 's#/data/#${SD_EXT_DIRECTORY}#' /dev/${d}_flist
       for f in `cat /dev/${d}_flist`
       do
          mv ${f} /data/${d}
       done
       log -p e -t apps2sd "Moved apps back to /data/${d}"
       # in some bizzarre scenario this can lead to /data/app being on SD
       # and /data/app-private on phone mem (or vice-versa) 
   fi
   rm /dev/${d}_flist
done

setprop cm.a2sd.active 1
log -p i -t apps2sd "Apps2SD activated"

# Mount bind /data/data to SD 

if [ ! -d ${SD_EXT_DIRECTORY}/data ]
then
    install -m 771 -o 1000 -g 1000 -d ${SD_EXT_DIRECTORY}/data
fi

busybox mount --bind ${SD_EXT_DIRECTORY}/data /data/data
if [ $? -eq 0 ]
then
    log -p i -t apps2sd "${SD_EXT_DIRECTORY}/data binded to /data/data"
else
    log -p e -t apps2sd "Failed to bind ${SD_EXT_DIRECTORY}/data on /data/data"
    exit 1
fi
