#!/system/bin/sh
#
# NOTICE:
# Although I've written this file from scratch (well almost =o)
# credits for this should go to Firerat and
# flames should go to me =o)
# NLJ
# 20100822 - NLJ
# - first version heavily based on Firerat work
# 20100829 - NLJ
# - auto-disable swap when CompCache is active
# - added check for FroYo (would gladly check for CM6 but there is no prop
#   for that

if [ -e /data/property/persist.sys.swap ]
then
    SWAPPROP=`getprop  persist.sys.swap`
else
    SWAPPROP=`getprop ro.swap.default`
    setprop persist.sys.swap $SWAPPROP
fi # Idea taken from bin/handle_compcache

if [ -e /data/property/persist.service.compcache ]
then
    CCPROP=`getprop persist.service.compcache`
else
    CCPROP=`getprop ro.compcache.default`
    setprop persist.service.compcache $CCPROP
fi # bin/handle_compcache 
#FIXME: one day i should try and see if above is needed at all
    

if [ $CCPROP -gt 0 ]
then
    log -p i -t swap "CompCache is enabled. Swap will NOT be activated."
    exit 0
fi

if [ $SWAPPROP -eq 0 ]
then
    log -p i -t swap "Swap disabled."
    exit 0
fi

SWAPPINESS=20

# Find swap partition
SWAP=`fdisk -l /dev/block/mmcblk0 | awk '/^\// && $5 == 82 {print $1;exit;}'`


if [ -n $SWAP ]
then
    swapon $SWAP 2>/dev/null
    if [ $? -eq 0 ]
    then
        echo $SWAPPINESS > /proc/sys/vm/swappiness
        log -p i -t swap "Swap activated on ${SWAP} with ${SWAPPINESS} swappiness"
    else
        log -p e -t swap "swapon ${SWAP} failed"
    fi
fi
