#!/system/bin/sh
#
# NOTICE:
# Although I've written this file from scratch (well almost =o)
# credits for this should go to Firerat and
# flames should go to me =o)
# NLJ
#
# Changelog is in git:
# http://github.com/biffmod/vendor_BiffMod/commits/master/prebuilt/common/etc/init.d/08swap
#

PERSIST_CC=persist.service.compcache
RO_CC=ro.compcache.default
PERSIST_SWAP=persist.sys.swap
RO_SWAP=ro.swap.default
SWAPPINESS=20

if [ -e /data/property/$PERSIST_CC ]
then
    CCPROP=`getprop $PERSIST_CC`
else
    CCPROP=`getprop $RO_CC`
    setprop $PERSIST_CC $CCPROP
fi # bin/handle_compcache 
#FIXME: one day i should try and see if above is needed at all
    
if [ $CCPROP -gt 0 ]
then
    log -p i -t swap "CompCache is enabled. NOT enabling Swap."
    exit 0
fi

# Swap is type 82
SWAP=`fdisk -l /dev/block/mmcblk0 | awk '/^\// && $5 == 82 {print $1;exit;}'`

if [ -z $SWAP ]
then
    log -p i -t swap "Swap partition not found"
    setprop $PERSIST_SWAP -1
    exit 0
fi

if [ -e /data/property/$PERSIST_SWAP ]
then
    SWAPPROP=`getprop  $PERSIST_SWAP`
    if [ $SWAPPROP -eq -1 ]
    then
        SWAPPROP=`getprop $RO_SWAP`
        setprop $PERSIST_SWAP $SWAPPROP
    fi
else
    SWAPPROP=`getprop $RO_SWAP`
    setprop $PERSIST_SWAP $SWAPPROP
fi # Idea taken from bin/handle_compcache


if [ $SWAPPROP -eq 0 ]
then
    log -p i -t swap "Swap disabled."
    exit 0
fi

swapon $SWAP 2>/dev/null
if [ $? -eq 0 ]
then
    echo $SWAPPINESS > /proc/sys/vm/swappiness
    log -p i -t swap "Swap enabled on ${SWAP} with ${SWAPPINESS} swappiness"
else
    log -p e -t swap "swapon ${SWAP} failed"
fi
