#!/bin/sh
# add android-wireless-tether for root users
#
# this is intended to run just after squisher by make biffmod-ota 

OUT_TARGET_HOST=`uname -a | grep Darwin`
if [ -z "$OUT_TARGET_HOST" ]
then
    OUT_TARGET_HOST=linux-x86
    MD5=md5sum
else
    OUT_TARGET_HOST=darwin-x86
    MD5=md5
fi

# Determine what to name the new signed package
if [ -z "$CYANOGEN_NIGHTLY" ]; then
    MODVERSION=`sed -n -e'/ro\.modversion/s/^.*CyanogenMod-6-//p' $OUT/system/build.prop`
    : ${MODVERSION:=nightly-BiffMod}
    OUTFILE=$OUT/update-$MODVERSION-signed.zip
else
    OUTFILE=$OUT/update-squished.zip
fi

echo $OUTFILE

if [ -z "$OUT" -o ! -d "$OUT" ]; then
    echo "requires a full build enviroment (\$OUT not set)"
    exit -1
fi
if [ -z "$OUTFILE" -o ! -e "$OUTFILE" ]; then
    echo "squisher output missing; please run squisher before this app"
    exit -1
fi

DEST_DIRNAME=`dirname "$OUTFILE"`
mkdir -p "$DEST_DIRNAME/wifi-tether-tmp/system/app"
cp vendor/biffmod/wireless_tether_2_0_2.apk "$DEST_DIRNAME/wifi-tether-tmp/system/app/wireless_tether_2_0_2.apk"
(
    cd "`dirname $OUTFILE`"
    mv "`basename $OUTFILE`" "wifi-tether-tmp/"
    cd "wifi-tether-tmp"
    zip -m "`basename $OUTFILE`" system/app/wireless_tether_2_0_2.apk
)

echo apk added, time to resign
SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
java -Xmx512m \
    -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
    -w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
       "$DEST_DIRNAME/wifi-tether-tmp/`basename $OUTFILE`" $OUTFILE

echo cleanup
rm -rf "$DEST_DIRNAME/wifi-tether-tmp"

echo new_checksum
(
img=`basename $OUTFILE`
cd `dirname $OUTFILE`
$MD5 $img >$img.md5sum
echo
echo "Package complete: $OUTFILE"
cat $img.md5sum
echo
)

